create table author (
    id   bigint generated by default as identity primary key,
    name varchar(255) not null
);

create table tag (
    id   bigint generated by default as identity primary key,
    name varchar(255) not null
);

create table book (
    id          bigint generated by default as identity primary key,
    title       varchar(255) not null,
    description varchar(2000),
    author_id   bigint references author (id)
);

create table book_tag (
    book_id bigint not null references book (id),
    tag_id  bigint not null references tag (id),
    primary key (book_id, tag_id)
);
