-- Author <-> Book becomes many-to-many; drop the old single-author FK
alter table book
    drop column author_id;

create table author_book (
    author_id bigint not null references author (id),
    book_id   bigint not null references book (id),
    primary key (author_id, book_id)
);

-- New Editor entity and its many-to-many link to Book
create table editor (
    id   bigint generated by default as identity primary key,
    name varchar(255) not null
);

create table editor_book (
    editor_id bigint not null references editor (id),
    book_id   bigint not null references book (id),
    primary key (editor_id, book_id)
);
