-- Author and Editor model *people*, whose names legitimately collide (two
-- different people can share a name), so uniqueness on their name was wrong.
-- Publishing houses are organizations with (near-)controlled names, so the
-- publisher gets its own table with a unique name, and a book has one publisher.

-- Drop the incorrect person-name uniqueness (tag stays unique: it is a label).
ALTER TABLE author DROP CONSTRAINT author_name_unique;
ALTER TABLE editor DROP CONSTRAINT editor_name_unique;

-- New publisher entity: a book has at most one publisher (many-to-one).
CREATE TABLE publisher (
    id   bigint generated by default as identity primary key,
    name varchar(255) not null,
    CONSTRAINT publisher_name_unique UNIQUE (name)
);

ALTER TABLE book
    ADD COLUMN publisher_id bigint,
    ADD CONSTRAINT book_publisher_id_fkey
        FOREIGN KEY (publisher_id) REFERENCES publisher (id) ON DELETE SET NULL;

-- Index the FK column so "books by publisher" lookups and the ON DELETE SET NULL
-- check don't scan book.
CREATE INDEX idx_book_publisher ON book (publisher_id);
